---

- name: Using roles (old style)
  hosts: "{{ hg | default('all') }}"
  gather_facts: true
  pre_tasks:

    - name: Pre task
      debug:
        msg: "{{ inventory_hostname }} pre-task 1"
        verbosity: "{{ pv | default(1) }}"
      changed_when: true
      notify: handler_1

  roles:

    - ar_olug_hello_world
    - ar_olug_hello_world

  post_tasks:

    - name: Post Task
      debug:
        msg: "{{ inventory_hostname }} post-task 1"
        verbosity: "{{ pv | default(1) }}"

  handlers:

    - name: Handler 1
      debug:
        msg: "{{ inventory_hostname }} handler 1"
        verbosity: "{{ pv | default(1) }}"
      listen: handler_1