---

- name: Using roles (new style)
  hosts: "{{ hg | default('all') }}"
  gather_facts: true
  tasks:

    - name: Pre task
      debug:
        msg: "{{ inventory_hostname }} pre-task 1"
        verbosity: "{{ pv | default(1) }}"
      changed_when: true
      notify: handler_1

    - name: apply hello world role
      import_role:
        name: ar_olug_hello_world

    - name: middle Task
      debug:
        msg: "{{ inventory_hostname }} middle-task 1"
        verbosity: "{{ pv | default(1) }}"

    - name: apply hello world role again
      import_role:
        name: ar_olug_hello_world

    - name: Post Task
      debug:
        msg: "{{ inventory_hostname }} post-task 1"
        verbosity: "{{ pv | default(1) }}"

  handlers:

    - name: Handler 1
      debug:
        msg: "{{ inventory_hostname }} handler 1"
        verbosity: "{{ pv | default(1) }}"
      listen: handler_1
